import {
    DefaultAvatar,
    Logo,
    FooterLogo,
    FeedbackLogo,
    CreateUser,
    ContactLogo,
    ThankLetter,
    WatchVideoLogo,
    Slide1,
    Slide2,
    Slide3,
    Event1,
    Event2,
    Event3,
    QuillLetter,
    QuillLetterReflect,
    ReadingBanner,
} from "./images";

const images = {
    DefaultAvatar,
    Logo,
    FooterLogo,
    CreateUser,
    FeedbackLogo,
    ContactLogo,
    ThankLetter,
    WatchVideoLogo,
    Slide1,
    Slide2,
    Slide3,
    Event1,
    Event2,
    Event3,
    QuillLetter,
    QuillLetterReflect,
    ReadingBanner,
};

export { images, DefaultAvatar };
